apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak-pep.fullname" . }}
  labels:
    {{- include "keycloak-pep.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "keycloak-pep.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/configMap: {{ include (print $.Template.BasePath "/configMap.yml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "keycloak-pep.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: app-config
              mountPath: "/deployments/application.properties"
              readOnly: true
              subPath: application.properties
      volumes:
        - name: app-config
          configMap:
            name: {{ include "keycloak-pep.fullname" . }}-config
