apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak-pep.fullname" . }}
  labels:
    {{- include "keycloak-pep.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "keycloak-pep.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/configMap: {{ include (print $.Template.BasePath "/configMap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "keycloak-pep.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - result=$(curl -s -i localhost:{{ .Values.service.port }} | head -1 | cut -d" " -f2) && [ "$result" = "403" ]
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - result=$(curl -s -i localhost:{{ .Values.service.port }} | head -1 | cut -d" " -f2) && [ "$result" = "403" ]
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: app-config
              mountPath: "/deployments/application.properties"
              readOnly: true
              subPath: application.properties
      volumes:
        - name: app-config
          configMap:
            name: {{ include "keycloak-pep.fullname" . }}-config
