{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "keycloak-pep.fullname" . }}
spec:
  to:
    kind: Service
    name: {{ include "keycloak-pep.fullname" . }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
