nameOverride: "air-quality"

## configuration for the init-containers 
init:
  ## configuration for the keycloak init-container
  keycloak:
    # -- should the init-container be enabled
    enabled: true 
    ## configuration of the image to be used
    image:
      # -- subscription init image name
      # ref: https://quay.io/fiware/v2-subscription-init
      repository: docker.io/bitnami/keycloak-config-cli
      # -- tag of the image to be used
      tag: 5.2.0-debian-10-r9
      # -- specification of the image pull policy
      pullPolicy: IfNotPresent
    # -- URL of the keycloak that will be configured from the init container
    url: http://keycloak
    admin:
      # -- Keycloak admin user with permissions to create users
      user: fiwareAdmin
      # -- Keycloak admin password with permissions to create users
      password: fiwareAdmin
    airqualitySimulator:
      # -- New username to create in Keycloak for the Air Quality app
      user: airqualityapp-user
      # -- Password for the new username to create in Keycloak for the Air Quality app
      password: airqualityapp