{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "grafana.fullname" . }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
  {{- if .Values.route.annotations }}
  annotations:
    {{- with .Values.route.annotations }}
      {{- toYaml . | nindent 4 }}
      {{- end }}
  {{- end }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host}}
  {{- end }}
  {{- if .Values.route.tls }}
  tls:
  {{- with .Values.route.tls }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  to:
    kind: Service
    name: {{ template "grafana.fullname" . }}
{{- end }}