apiVersion: v1
kind: Secret
metadata:
  name: {{ template "grafana.fullname" . }}-datasources
  labels:
    grafana_datasource: {{ template "grafana.fullname" . }}
    {{- include "grafana.labels" . | nindent 4 }}
type: Opaque
stringData:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
      - name: prometheus-datasource
        type: prometheus
        access: proxy
        orgId: 1
        uid: "2"
        url: {{ .Values.datasources.prometheus.url | default "http://prometheus:9090" }}
        basicAuth: false
        withCredentials: false
        isDefault: false
        version: 1
        editable: true
        jsonData:
          httpHeaderName1: 'Authorization'
          timeInterval: 30s
          tlsSkipVerify: true
        secureJsonData:
          httpHeaderValue1: ''

# Bearer Token: /run/secrets/kubernetes.io/serviceaccount/token
