apiVersion: v1
kind: Secret
metadata:
  name: {{ template "grafana.fullname" . }}-datasources
  labels:
    grafana_datasource: {{ template "grafana.fullname" . }}
    {{- include "grafana.labels" . | nindent 4 }}
type: Opaque
stringData:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus-Thanos
        access: proxy
        editable: true
        isDefault: true
        jsonData:
          httpHeaderName1: 'Authorization'
          timeInterval: 5s
          tlsSkipVerify: true
        secureJsonData:
          httpHeaderValue1: 'Bearer $__file{/run/secrets/kubernetes.io/serviceaccount/token}'
        type: prometheus
        url: {{ .Values.datasources.prometheus.url | default "http://prometheus:9090" }}
# Bearer Token: /run/secrets/kubernetes.io/serviceaccount/token
