apiVersion: v2
name: mongo-db
description: Chart holder for argo-cd

type: application
version: 1.0.0
appVersion: "4.4.12" # MongoDB version 4.4.12

dependencies:
- name: mongodb
  version: 12.1.31
  repository: https://charts.bitnami.com/bitnami

maintainers:
  - name: Felipe Roca
    email: felipe@hopu.org
  - name: Alvaro Lopez
    email: alopezme@redhat.com
  - name: Stefan Wiedemann 
    email: stefan.wiedemann@fiware.org
