
mongodb:
  global:
    nameOverride: "mongodb-orion"
    fullnameOverride: "mongodb-orion"
  auth:
    enabled: true
    rootPassword: test
  architecture: replicaset
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
  resources:
    limits:
      cpu: 500m #400m
      memory: 1.5Gi #1024Mi
    requests:
      cpu: 50m #400m
      memory: 300Mi #1024Mi
  persistence:
    enabled: true
    size: 8Gi
  arbiter:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    podLabels:
      marinera/platform: fiware
      marinera/component: core
      marinera/subcomponent: persistence
      marinera/product: mongodb
    resources:
      limits:
        cpu: 500m #400m
        memory: 1.5Gi #1024Mi
      requests:
        cpu: 50m #400m
        memory: 300Mi #1024Mi
  systemLogVerbosity: 1
  podLabels:
    marinera/platform: fiware
    marinera/component: core
    marinera/subcomponent: persistence
    marinera/product: mongodb
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
    resources:
      limits:
        cpu: 200m
        memory: 500Mi 
      requests:
        cpu: 50m 
        memory: 50Mi 
