
mongodb:
  global:
    nameOverride: "mongodb-orion"
    fullnameOverride: "mongodb-orion"
  auth:
    enabled: true
    #existingSecret: mongodb-secret
    rootPassword: test
  architecture: replicaset
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
  resources:
    limits:
      cpu: 400m
      memory: 1024Mi
    requests:
      cpu: 400m
      memory: 1024Mi
  persistence:
    enabled: true
    size: 8Gi
  arbiter:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false