apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: {{ .Values.nameOverride }}-timescale-datasource
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  datasources:
    - name: timescale-datasource
      type: postgres
      access: proxy
      orgId: 1
      uid: "3"
      user: {{ .Values.datasources.timescale.credentials.username | default "admin" }}
      url: {{ .Values.datasources.timescale.url | default "tsdb:5432" }}
      database: {{ .Values.datasources.timescale.database | default "postgres" }}
      secureJsonData:
        password: {{ .Values.datasources.timescale.credentials.password | default "admin" }}
      basicAuth: false
      withCredentials: false
      isDefault: false
      jsonData:
        sslmode: disable
        postgresVersion: 1200
        timescaledb: true
      version: 1
      editable: true 
  name: {{ .Values.nameOverride }}-timescale-datasource.yaml
