apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.nameOverride }}
labels:
    {{- include "grafana.labels" . | nindent 4 }}
stringData:
  GF_INSTALL_PLUGINS: "{{ join "," .Values.grafana.plugins  }}"
  GF_AUTH_ANONYMOUS_ENABLED: "{{ .Values.grafana.security.anonymous.enabled }}"
  GF_USERS_DEFAULT_THEME: "light"
