apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-datasources
  annotations:
    {{ if .Values.scope.namespace }}
    sealedsecrets.bitnami.com/namespace-wide: "true"
    {{ else }}
    sealedsecrets.bitnami.com/cluster-wide: "true"
    {{ end }}
  labels:    
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  template:
    type: Opaque
    metadata:
      labels:
        grafana_datasource: grafana
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    data:
      datasources.yaml: |-
        apiVersion: 1
        datasources:
          - name: orion-datasource
            type: orion-datasource
            access: proxy
            orgId: 1
            uid: "2"
            url: {{ .Values.grafana.datasourcesNotEncrypted.orion.url | default "http://orion:1026" }}
            jsonData:
              orionPaginationLimit: 1000
            basicAuth: false
            withCredentials: false
            isDefault: false
            version: 1
            editable: true
          - name: timescale-datasource  
            type: postgres
            access: proxy
            orgId: 1
            uid: "3"
            user: {{ .Values.grafana.datasourcesNotEncrypted.timescale.credentials.username | default "admin" }}
            url: {{ .Values.grafana.datasourcesNotEncrypted.timescale.url | default "tsdb:5432" }}
            database: {{ .Values.grafana.datasourcesNotEncrypted.timescale.database | default "postgres" }}
            secureJsonData:
              password: $__file{/etc/grafana/secrets/timescale-password}
            basicAuth: false
            withCredentials: false
            isDefault: false
            jsonData:
              sslmode: disable
              postgresVersion: 1200
              timescaledb: true
            version: 1
            editable: true 