apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb-secret
  annotations:
    {{ if .Values.scope.namespace }}
    sealedsecrets.bitnami.com/namespace-wide: "true"
    {{ else }}
    sealedsecrets.bitnami.com/cluster-wide: "true"
    {{ end }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  template:
    type: Opaque
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
  encryptedData:
    mongodb-root-password: {{ .Values.mongodb.mongodbRootPassword }}
    mongodb-replica-set-key: {{ .Values.mongodb.mongodbReplicaSetKey }}