apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tsdb-password
  annotations:
    {{ if .Values.scope.namespace }}
    sealedsecrets.bitnami.com/namespace-wide: "true"
    {{ else }}
    sealedsecrets.bitnami.com/cluster-wide: "true"
    {{ end }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  template:
    type: Opaque
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
  encryptedData:
    tsdb-password: {{ .Values.grafana.datasources.timescale.credentials.password }}