apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tsdb-credentials
  annotations:
    {{ if .Values.scope.namespace }}
    sealedsecrets.bitnami.com/namespace-wide: "true"
    {{ else }}
    sealedsecrets.bitnami.com/cluster-wide: "true"
    {{ end }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: tsdb-timescaledb
    cluster-name: tsdb
spec:
  template:
    type: Opaque
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
  encryptedData:
    PATRONI_SUPERUSER_PASSWORD: {{ .Values.timescaledb.PATRONI_SUPERUSER_PASSWORD }}
    PATRONI_REPLICATION_PASSWORD: {{ .Values.timescaledb.PATRONI_REPLICATION_PASSWORD }}
    PATRONI_admin_PASSWORD: {{ .Values.timescaledb.PATRONI_admin_PASSWORD }}