apiVersion: v2
name: quantumleap
description: A Helm chart for Kubernetes to deploy QuantumLeap using the official Helm Chart.
type: application
version: 1.0.0
appVersion: "0.9.0-PRE" # QuantumLeap version
keywords:
  - quantumleap
  - helm
  - chart
sources:
  - https://github.com/FIWARE-Ops/marinera/tree/main/applications/quantumleap/chart
dependencies:
- name: quantumleap
  version: 0.1.18
  repository: https://orchestracities.github.io/charts/
maintainers:
  - name: Felipe Roca
    email: felipe@hopu.org
  - name: Alvaro Lopez
    email: alopezme@redhat.com
  - name: Stefan Wiedemann 
    email: stefan.wiedemann@fiware.org
