quantumleap:
  # Default values for quantumleap.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

  # -- Number of replicas
  replicaCount: 2

  init:
    image:
      # -- Container image to deploy
      repository: quay.io/fiware/quantumleap-pg-init
      # -- Container image tag to deploy
      tag: 0.9.0-PRE
  image:
    # -- Container image to deploy
    repository: quay.io/fiware/quantumleap
    # -- Container image tag to deploy
    tag: 0.9.0-PRE
    # -- Pull policy of the image
    pullPolicy: IfNotPresent

  # health checks are fixed in ql master
  readinessProbe:
    enabled: true
  livenessProbe:
    enabled: true

  updateStrategy:
    rollingUpdate:
      # -- Max replicas available when upgrading
      maxUnavailable: 1
    # -- Type of update strategy
    type: RollingUpdate

  autoscaling:
    # -- Autoscaling Enabled/Disabled
    enabled: false
    # -- Autoscaling min replicas
    minReplicas: 2
    # -- Autoscaling max replicas
    maxReplicas: 6
    # -- Autoscaling target average utilization
    targetAverageUtilization: 50

  service:
    # -- Name of the service
    name: quantumleap
    # -- Type of the service
    type: ClusterIP
    # -- Port of the service
    externalPort: 80
    # -- Port exposed in the application
    internalPort: 8668

  database:
    # -- empty all values to disable cratedb(as enabled by default on the chart)
    crate:
      host:
      port:
      defaultdb:
    timescale:
      # -- Database hostname. Always connect to tsdb service, which is behind the master. Patroni manages the labeling of the Pods.
      host: tsdb
      # --  Database port
      port: 5432
      # -- Database name inside Timescale
      name: postgres
      # -- User to connect to the database
      user: postgres
      # -- Password for the user to connect to the database
      password: test
      # -- SSL connection to Timescale. Not working with SSL for the moment
      ssl: false

  config:
    # -- Backend database. Default is timescale
    default-backend: "timescale"

  resources:
    limits:
      cpu: 500m
      memory: 250Mi
    requests:
      cpu: 10m
      memory: 50Mi

  geocoding:
    # -- Caching can be disabled by setting the host to empty
    redisHost:
  runtime:
    logLevel: "WARNING"
