quantumleap:
  # Default values for quantumleap.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.
  replicaCount: 2
  image:
    repository: smartsdk/quantumleap
    tag: 0.8.0
    pullPolicy: IfNotPresent

  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate

  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 6
    targetAverageUtilization: 50

  service:
    name: quantumleap
    type: ClusterIP
    externalPort: 80
    internalPort: 8668

  affinity: {}

  database:
    timescale:
      host: tsdb
      port: 5432
      name: quantumleap
      user: admin
      password: PxGr9EvXvbKvEjwM
      ssl: false

  config:
    tenants: {}
    default-backend: "Timescale"

  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi