apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-auth-secret
  namespace: argocd
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: fiware-cluster-secrets
    kind: ClusterSecretStore
  target:
    name: argocd-auth-secret
  dataFrom:
    - extract:
        key: fiware/argocd-auth-secret
