kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "airquality-simulator.fullname" . }}-cm
  labels:
    {{ include "airquality-simulator.labels" . | nindent 4 }}
data:
  application.yaml: |-
    {{ .Values.config | toYaml | nindent 4 }}