{{- if .Values.init.subscription.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "airquality-simulator.fullname" . }}-sub-cm
  labels:
    {{ include "airquality-simulator.labels" . | nindent 4 }}
data:
  create-subscription.sh: |-
    curl -X POST "{{ .Values.config.general.brokerUrl }}/v2/subscriptions" \
      -H  "accept: application/json" \
      -H  "Content-Type: application/json" \
      -H  "Fiware-Service: {{ .Values.config.general.fiwareService }}" \
      -H  "Fiware-ServicePath: {{ .Values.config.general.fiwareServicePath }}" \
      -d "{ 
            \"id\": \"test-id\",
            \"description\": \"Subscription for simulated air-quality data\",
            \"subject\": {
                \"entities\": [      {
                  \"idPattern\": \".*\",
                  \"type\": \"{{ .Values.init.subscription.entityType }}
        {{- end -}}\"
                   }
                ]
            },
            \"notification\": {
              \"httpCustom\": {
                \"url\": \"{{ .Values.init.subscription.quantumLeapUrl }}/v2/notify\",
                \"headers\": {
                  \"fiware-service\" : \"{{ .Values.config.general.fiwareService }}\",
                  \"fiware-servicepath\" : \"{{ .Values.config.general.fiwareServicePath }}\"
                },
                \"attrs\": [
                  \"co\", \"so2\", \"no2\", \"o3\", \"pm1\",\"pm25\",\"Ppm10\"
                ]
              }
            }
          }"
{{- end -}}