source: https://github.com/FIWARE-Ops/marinera
release: demo
destination_namespace: &destination demo
branch: &branch main
secretsEnabled: &secretsEnabled false

applications:
  # Dont change mongodb name, current orion config relies on it.
  - name: mongodb-orion
    enabled: true
    source_path: applications/mongodb/chart
    source_ref: *branch
    destination: *destination
    secretsReady: true # Don't change. This means that the chart is prepared to use Sealed Secrets
    helm_values:
    - values.yaml

  - name: orion-ld
    enabled: true
    source_path: applications/orion-ld/chart
    source_ref: *branch
    destination: *destination
    secretsReady: true # Don't change. This means that the chart is prepared to use Sealed Secrets
    helm_values:
    - values.yaml

  - name: timescaledb-single
    # Dont override, will break the tests.
    releaseName: tsdb
    enabled: true
    source_path: applications/timescaledb-single/chart
    source_ref: *branch
    destination: *destination
    secretsReady: true # Don't change. This means that the chart is prepared to use Sealed Secrets
    helm_values:
    - values.yaml

  - name: quantumleap
    enabled: true
    source_path: applications/quantumleap/chart
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml

  - name: grafana
    enabled: true
    source_path: applications/grafana/chart
    source_ref: *branch
    destination: *destination
    secretsReady: true # Don't change. This means that the chart is prepared to use Sealed Secrets
    helm_values:
    - values.yaml

  - name: air-quality
    enabled: true
    source_path: applications/air-quality-app/chart
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml

  - name: keycloak
    enabled: true
    source_path: applications/keycloak/chart
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml

  - name: keycloak-pep
    enabled: true
    source_path: applications/keycloak-pep/chart
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml

  - name: grafana-metrics
    enabled: true
    source_path: applications/grafana-metrics/chart
    source_ref: *branch
    destination: *destination
    secretsReady: true # Don't change. This means that the chart is prepared to use Sealed Secrets
    helm_values:
    - values.yaml

  - name: airquality-simulator
    enabled: true
    source_path: applications/airquality-simulator/chart
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml

  - name: marinera-secrets
    enabled: *secretsEnabled
    source_path: secrets
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml
