---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: patch-operator
  namespace: patch-operator
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: patch-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: patch-operator.v0.1.9
  