nameOverride: "grafana"
grafana:
  admin:
    existingSecret: "grafana-admin-user"
    userKey: admin-user
    passwordKey: admin-password
  grafana.ini:
    log:
      level: warn
    log.console:
      format: json
    plugins:
      allow_loading_unsigned_plugins: orion-datasource
    users:
      default_theme: light # dark | light
    auth.anonymous:
      enabled: false
  initChownData:
    enabled: false
  persistence:
    enabled: false
  plugins:
    - grafana-simple-json-datasource
    - yesoreyeram-infinity-datasource
    - https://github.com/HOP-Ubiquitous/orion-datasource/releases/download/1.0.0/orion-datasource.zip;orion-datasource
  rbac:
    pspEnabled: false
    namespaced: true
    extraRoleRules:
    - apiGroups: ["route.openshift.io"]
      resources: ["routes"]
      verbs: ["get","list"]
  securityContext: ""
  extraContainerVolumes:
    - name: env-dir
      emptyDir: {}
  extraVolumeMounts: 
    - name: env-dir
      mountPath: /env
      readOnly: true

  sidecar:
    dashboards:
      enabled: true
      SCProvider: true
      label: grafana_dashboard
      labelValue: grafana
      orgid: 1
      defaultFolderName: default
    datasources:
      enabled: true
      label: grafana_datasource
      labelValue: grafana
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 10Mi
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'dashboards'
        orgId: 1
        folder: 'Dashboards'
        type: file
        disableDeletion: true
        editable: false
        options:
          path: /tmp/dashboards/dashboards  # should match sidecar.dashboards.defaultFolderName
      - name: 'air-quality'
        orgId: 1
        folder: 'Air Quality'
        type: file
        disableDeletion: true
        editable: false
        options:
          path: /tmp/dashboards/air-quality  # should match sidecar.dashboards.defaultFolderName

  podLabels:
    marinera/platform: fiware
    marinera/component:	visualization
    marinera/subcomponent: ui
    marinera/product: grafana
  serviceMonitor:
    enabled: true
    interval: 30s
  env:
    GF_PANELS_DISABLE_SANITIZE_HTML: true

  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 10m
      memory: 100Mi

  extraInitContainers:
    - name: get-route
      image: bitnami/kubectl
      command:
        - /bin/sh
        - -c
        - |
          host=$(kubectl get route keycloak -o jsonpath={.spec.host})
          echo KEYCLOAK_HOST=$host >> /env/kc.env 
      volumeMounts:
      - name: env-dir
        mountPath: "/env"

  command: ["/bin/sh", "-c", "source /env/kc.env | /run.sh"]
admin:
  secured: false
  # -- Admin username
  username: fiwareAdmin
  # -- Admin password
  password: fiwareAdmin

route:
  # -- To enable the OpenShift route
  enabled: true

datasources:
  orion:
    # -- Orion URL
    url: "http://orion-ld:1026"
  timescale:
    # -- Timescale URL
    url: tsdb
    # -- Timescale database name
    database: postgres
    credentials:
      # -- Timescale database username
      username: postgres
      # -- Timescale database password
      password: test

tests:
  enabled: true
