nameOverride: "grafana"
grafana:
  admin:
    existingSecret: "grafana-admin-user"
    userKey: admin-user
    passwordKey: admin-password
  grafana.ini:
    log:
      level: warn
    log.console:
      format: json
    plugins:
      allow_loading_unsigned_plugins: orion-datasource
    users:
      default_theme: light # dark | light
    auth.anonymous:
      enabled: false
    auth.generic_oauth:
      enabled: true
      name: Keycloak
      allow_sign_up: true
      scopes: profile,email,groups
      auth_url: https://keycloak-feature-add-grafana-oauth.apps.fiware-spain.emea-1.rht-labs.com/realms/fiware-server/protocol/openid-connect/auth
      token_url: https://keycloak-feature-add-grafana-oauth.apps.fiware-spain.emea-1.rht-labs.com/realms/fiware-server/protocol/openid-connect/token
      api_url: https://keycloak-feature-add-grafana-oauth.apps.fiware-spain.emea-1.rht-labs.com/realms/fiware-server/protocol/openid-connect/userinfo
      client_id: grafana
      client_secret: secret
      # role_attribute_path: contains(groups[*], 'grafana-admin') && 'Admin' || contains(groups[*], 'grafana-dev') && 'Editor' || 'Viewer'
      role_attribute_path: resource_access.grafana.roles[0]
  initChownData:
    enabled: false
  persistence:
    enabled: false
  plugins:
    - grafana-simple-json-datasource
    - yesoreyeram-infinity-datasource
    - https://github.com/HOP-Ubiquitous/orion-datasource/releases/download/1.0.0/orion-datasource.zip;orion-datasource
  rbac:
    pspEnabled: false
    namespaced: true
  securityContext: ""

  sidecar:
    dashboards:
      enabled: true
      SCProvider: true
      label: grafana_dashboard
      labelValue: grafana
      orgid: 1
      defaultFolderName: default
    datasources:
      enabled: true
      label: grafana_datasource
      labelValue: grafana
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 10Mi
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'dashboards'
        orgId: 1
        folder: 'Dashboards'
        type: file
        disableDeletion: true
        editable: false
        options:
          path: /tmp/dashboards/dashboards  # should match sidecar.dashboards.defaultFolderName
      - name: 'air-quality'
        orgId: 1
        folder: 'Air Quality'
        type: file
        disableDeletion: true
        editable: false
        options:
          path: /tmp/dashboards/air-quality  # should match sidecar.dashboards.defaultFolderName

  podLabels:
    marinera/platform: fiware
    marinera/component:	visualization
    marinera/subcomponent: ui
    marinera/product: grafana
  serviceMonitor:
    enabled: true
    interval: 30s
  env:
    GF_PANELS_DISABLE_SANITIZE_HTML: true

  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 10m
      memory: 100Mi


admin:
  secured: false
  # -- Admin username
  username: fiwareAdmin
  # -- Admin password
  password: fiwareAdmin

route:
  # -- To enable the OpenShift route
  enabled: true

datasources:
  orion:
    # -- Orion URL
    url: "http://orion-ld:1026"
  timescale:
    # -- Timescale URL
    url: tsdb
    # -- Timescale database name
    database: postgres
    credentials:
      # -- Timescale database username
      username: postgres
      # -- Timescale database password
      password: test

tests:
  enabled: true
