orion-ld:
  broker:
    db:
      hosts:
        - mongodb-orion-0.mongodb-orion-headless
        - mongodb-orion-1.mongodb-orion-headless
      replicaSet: rs0
      user: root
      auth:
        password: test
    logging:
      level: "WARN"
  deployment:
    replicaCount: 2
  mongo:
    # we want to use the individually deployed mongodb
    enabled: false
