orion-ld:
  broker:
    # Avoid inconsistencies when running more than 1 replica.
    subCacheIval: 1
    db:
      hosts:
        - mongodb-orion-0.mongodb-orion-headless
        - mongodb-orion-1.mongodb-orion-headless
      replicaSet: rs0
      user: root
      auth:
        password: test
    logging:
      level: "WARN"
  deployment:
    replicaCount: 2
    resources:
      limits:
        cpu: 250m #100m
        memory: 1GB #128Mi
      requests:
        cpu: 10m #100m
        memory: 50Mi #128Mi
  mongo:
    # we want to use the individually deployed mongodb
    enabled: false