{
 "title": "FIWARE Platform Metrics",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Orion-LD Last hour Rate Average",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Orion-LD - JSON Version Requests Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(orionld_versionRequests{namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Orion-LD - JSON Requests Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(orionld_jsonRequests{namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Orion-LD - Notifications Sent Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(orionld_notificationsSent{namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Orion-LD - Statistics Requests Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(orionld_statisticsRequests{namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Orion-LD Version Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Orion-LD - JSON Version Requests",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "orionld_versionRequests{namespace=\"$namespace\"}",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum by(job) (orionld_versionRequests{namespace=\"$namespace\"})",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Orion-LD - JSON Version Requests Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "sum(irate(orionld_versionRequests{namespace=~\"$namespace\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum(irate(orionld_versionRequests{namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "total"
      }
     ]
    }
   ]
  },
  {
   "title": "Orion-LD JSON Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Orion-LD JSON Requests",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "orionld_jsonRequests{namespace=\"$namespace\"}",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum by(job) (orionld_jsonRequests{namespace=\"$namespace\"})",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Orion-LD - JSON Requests Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "sum(irate(orionld_jsonRequests{namespace=~\"$namespace\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum(irate(orionld_jsonRequests{namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "total"
      }
     ]
    }
   ]
  },
  {
   "title": "Orion-LD Notification Sent",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Orion-LD - Notifications Sent",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "orionld_notificationsSent{namespace=\"$namespace\"}",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum by(job) (orionld_notificationsSent{namespace=\"$namespace\"})",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Orion-LD - Notifications Sent Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
     "targets": [
      {
       "expr": "sum(irate(orionld_notificationsSent{namespace=~\"$namespace\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum(irate(orionld_notificationsSent{namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "total"
      }
     ]
    }
   ]
  },
  {
   "title": "Orion-LD Statistics Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Orion-LD - Statistics Requests",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "orionld_statisticsRequests{namespace=\"$namespace\"}",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum by(job) (orionld_statisticsRequests{namespace=\"$namespace\"})",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Orion-LD - Statistics Requests Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
     "targets": [
      {
       "expr": "sum(irate(orionld_statisticsRequests{namespace=~\"$namespace\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum(irate(orionld_statisticsRequests{namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "total"
      }
     ]
    }
   ]
  }
 ]
}