# Default values for Keycloak.

nameOverride: "keycloak"

keycloak:
  replicaCount: 1

  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false

  auth:
    adminUser: fiwareAdmin
    adminPassword: fiwareAdmin

  postgresql:
  
