# Default values for Keycloak.

# nameOverride: "keycloak"

realm:
  grafana:
    rootUrl: https://grafana
    adminUrl: https://grafana
    redirectUris: 
      - https://grafana/
      - https://grafana-2/
    webOrigins: 
      - https://grafana/
      - https://grafana-2/
  orionPep:
    baseUrl: https://orion-ld
    adminUrl: https://orion-ld
    redirectUris: 
      - https://orion-ld/
      - https://orion-ld-2/
    webOrigins: 
      - https://orion-ld/
      - https://orion-ld-2/

keycloak:

  replicaCount: 1

  auth:
    adminUser: fiwareAdmin
    adminPassword: fiwareAdmin
  
  serviceAccount:
    create: true
  rbac:
    create: true
    rules:
      - apiGroups:
        - security.openshift.io
        resourceNames:
        - anyuid
        resources:
        - securitycontextconstraints
        verbs:
        - use

  keycloakConfigCli:
    enabled: true
    extraEnvVars:
      - name: IMPORT_FILES_LOCATIONS
        value: "/config/*"
    containerSecurityContext:
      enabled: false
    podSecurityContext:
      enabled: false
    existingConfigmap: keycloak-realm

  extraVolumeMounts:
    - name: profiles
      mountPath: /opt/bitnami/keycloak/conf/profile.properties
      subPath: profile.properties

  extraVolumes: 
    - name: profiles
      configMap:
        name: keycloak-profile
  
  extraEnvVars:
    - name: KEYCLOAK_LOG_LEVEL
      value: WARN
    #- name: KEYCLOAK_EXTRA_ARGS
    #  value: -Dkeycloak.log.console.output=json

  podLabels:
    marinera/platform: fiware
    marinera/component:	security
    marinera/subcomponent: auth
    marinera/product: keycloak

  # ingress:
  #   enabled: true
  #   hostname: ""

  service:
    type: ClusterIP


  postgresql:
    auth:
      username: bn_keycloak
      password: secretpassword
    primary:
      podSecurityContext:
        enabled: false
      containerSecurityContext:
        enabled: false
      podLabels:
        marinera/platform: fiware
        marinera/component:	security
        marinera/subcomponent: persistence
        marinera/product: postgresql
    readReplicas:
      podSecurityContext:
        enabled: false
      containerSecurityContext:
        enabled: false
    audit:
      clientMinMessages: warning
      
route:
  enabled: true
