# Default values for Keycloak.

# nameOverride: "keycloak"

keycloak:
  replicaCount: 1

  auth:
    adminUser: fiwareAdmin
    adminPassword: fiwareAdmin

  serviceAccount:
    create: true
  rbac:
    create: true
    rules:
      - apiGroups:
        - security.openshift.io
        resourceNames:
        - anyuid
        resources:
        - securitycontextconstraints
        verbs:
        - use

  ingress:
    enabled: true


  postgresql:
    primary:
      podSecurityContext:
        enabled: false
      containerSecurityContext:
        enabled: false
    readReplicas:
      podSecurityContext:
        enabled: false
      containerSecurityContext:
        enabled: false
      
