# Default values for Keycloak.

# nameOverride: "keycloak"

domain: test
uri:
  grafana: test


keycloak:
  replicaCount: 1

  auth:
    adminUser: fiwareAdmin
    adminPassword: fiwareAdmin

  extraEnvVars:
    - name: KEYCLOAK_EXTRA_ARGS
      value: "-Dkeycloak.profile.feature.upload_scripts=enabled"  

  serviceAccount:
    create: true
  rbac:
    create: true
    rules:
      - apiGroups:
        - security.openshift.io
        resourceNames:
        - anyuid
        resources:
        - securitycontextconstraints
        verbs:
        - use
  keycloakConfigCli:
    image: 
      tag: 5.2.0-debian-10-r4
    extraEnvVars:
      - name: IMPORT_FILES_LOCATIONS
        value: "/config/*"
      - name: LOGGING_LEVEL_ROOT
        value: "TRACE"
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    enabled: true
    existingConfigmap: keycloak-realm


  # ingress:
  #   enabled: true
  #   hostname: ""

  service:
    type: ClusterIP


  postgresql:
    auth:
      username: bn_keycloak
      password: secretpassword
    primary:
      podSecurityContext:
        enabled: false
      containerSecurityContext:
        enabled: false
    readReplicas:
      podSecurityContext:
        enabled: false
      containerSecurityContext:
        enabled: false
      
route:
  enabled: true