# Default values for Keycloak.

# nameOverride: "keycloak"

keycloak:
  replicaCount: 1

  auth:
    adminUser: fiwareAdmin
    adminPassword: fiwareAdmin

  serviceAccount:
    create: true
  rbac:
    create: true
    rules:
      - apiGroups:
        - security.openshift.io
        resourceNames:
        - anyuid
        resources:
        - securitycontextconstraints
        verbs:
        - use
  extraEnvVars:
    - name: KEYCLOAK_EXTRA_ARGS
      value: "-Dkeycloak.import=/config/realm.json"
  extraVolumeMounts:
    - name: config
      mountPath: "/config"
      readOnly: true
  extraVolumes:
    - name: config
      configMap:
        name: keycloak-realm
        items:
        - key: "realm.json"
          path: "realm.json"
  # ingress:
  #   enabled: true
  #   hostname: ""

  service:
    type: ClusterIP


  postgresql:
    auth:
      username: bn_keycloak
      password: secretpassword
    primary:
      podSecurityContext:
        enabled: false
      containerSecurityContext:
        enabled: false
    readReplicas:
      podSecurityContext:
        enabled: false
      containerSecurityContext:
        enabled: false
      
route:
  enabled: true