# Default values for Keycloak.

# nameOverride: "keycloak"

realm:
  grafana:
    rootUrl: https://grafana
    adminUrl: https://grafana
    redirectUris: 
      - https://grafana/
      - https://grafana-2/
    webOrigins: 
      - https://grafana/
      - https://grafana-2/
  orionPep:
    baseUrl: https://orion-ld
    adminUrl: https://orion-ld
    redirectUris: 
      - https://orion-ld/
      - https://orion-ld-2/
    webOrigins: 
      - https://orion-ld/
      - https://orion-ld-2/

keycloak:

  replicaCount: 1

  auth:
    adminUser: fiwareAdmin
    adminPassword: fiwareAdmin
  
  extraEnvVars:
    - name: KEYCLOAK_LOG_LEVEL
      value: ALL
    - name: KEYCLOAK_EXTRA_ARGS
      value: "-Dkeycloak.import=/opt/bitnami/keycloak/conf/realm.json"

  serviceAccount:
    create: true
  rbac:
    create: true
    rules:
      - apiGroups:
        - security.openshift.io
        resourceNames:
        - anyuid
        resources:
        - securitycontextconstraints
        verbs:
        - use

  extraVolumeMounts:
    - name: profiles
      mountPath: /opt/bitnami/keycloak/conf/profile.properties
      subPath: profile.properties
    - name: run
      mountPath: /opt/bitnami/scripts/keycloak/run.sh
      subPath: run.sh
    - name: realm
      mountPath: /opt/bitnami/keycloak/conf/realm.json
      subPath: realm.json
  extraVolumes: 
    - name: profiles
      configMap:
        name: keycloak-profile
    - name: realm
      configMap:
        name: keycloak-realm
    - name: run
      configMap:
        name: keycloak-run
        defaultMode: 0555


  # ingress:
  #   enabled: true
  #   hostname: ""

  service:
    type: ClusterIP


  postgresql:
    auth:
      username: bn_keycloak
      password: secretpassword
    primary:
      podSecurityContext:
        enabled: false
      containerSecurityContext:
        enabled: false
    readReplicas:
      podSecurityContext:
        enabled: false
      containerSecurityContext:
        enabled: false
      
route:
  enabled: true
