# Default values for Keycloak.

# nameOverride: "keycloak"

realm:
  grafana:
    rootUrl: https://grafana
    adminUrl: https://grafana
    redirectUris: 
      - https://grafana/
      - https://grafana-2/
    webOrigins: 
      - https://grafana/
      - https://grafana-2/
  orionPep:
    baseUrl: https://orion-ld
    adminUrl: https://orion-ld
    redirectUris: 
      - https://orion-ld/
      - https://orion-ld-2/
    webOrigins: 
      - https://orion-ld/
      - https://orion-ld-2/

keycloak:

  replicaCount: 1

  auth:
    adminUser: fiwareAdmin
    adminPassword: fiwareAdmin
  
  extraEnvVars:
    - name: KEYCLOAK_LOG_LEVEL
      value: ALL

  serviceAccount:
    create: true
  rbac:
    create: true
    rules:
      - apiGroups:
        - security.openshift.io
        resourceNames:
        - anyuid
        resources:
        - securitycontextconstraints
        verbs:
        - use

  extraVolumeMounts:
    - name: profiles
      mountPath: /opt/bitnami/keycloak/conf/profile.properties
      subPath: profile.properties
  extraVolumes: 
    - name: profiles
      configMap:
        name: keycloak-profile

  keycloakConfigCli:
    image: 
      tag: 5.2.0-debian-10-r4
    extraEnvVars:
      - name: IMPORT_FILES_LOCATIONS
        value: "/config/*"
      - name: LOGGING_LEVEL_ROOT
        value: "TRACE"
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    enabled: true
    existingConfigmap: keycloak-realm


  # ingress:
  #   enabled: true
  #   hostname: ""

  service:
    type: ClusterIP


  postgresql:
    auth:
      username: bn_keycloak
      password: secretpassword
    primary:
      podSecurityContext:
        enabled: false
      containerSecurityContext:
        enabled: false
    readReplicas:
      podSecurityContext:
        enabled: false
      containerSecurityContext:
        enabled: false
      
route:
  enabled: true
