apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: grafana-operator
  annotations:
    description: Template to deploy a Grafana operator on OCP.
    tags: grafana,community,operator
    iconClass: icon-cassandra
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
objects:
- apiVersion: project.openshift.io/v1
  kind: Project
  metadata:
    name: ${OPERATOR_NAMESPACE}
    annotations:
      openshift.io/description: "This project contains all the resources related to the operator of Grafana 3.5"
      openshift.io/display-name: "Grafana - Operator"
- apiVersion: operators.coreos.com/v1
  kind: OperatorGroup
  metadata:
    name: grafana
    namespace: ${OPERATOR_NAMESPACE}
  spec:
    targetNamespaces:
      - ${OPERATOR_NAMESPACE}
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: grafana-operator
    namespace: ${OPERATOR_NAMESPACE}
  spec:
    channel: v4
    installPlanApproval: Automatic
    name: grafana-operator
    source: community-operators
    sourceNamespace: openshift-marketplace
parameters:
- name: OPERATOR_NAMESPACE
  description: "The project where the operator will be installed."
  required: false
  value: "grafana"