apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: openshift-local-aoa
  namespace: argocd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: "{{ name }}-aoa"
    spec:
      project: default
      destination:
        namespace: argocd
        name: default/api-crc-testing:6443/kubeadmin
      source:
        path: "clusters/{{ name }}"
        repoURL: https://github.com/rh-impact/fiware-marinera.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
