apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-secret
  namespace: fiware
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: fiware-cluster-secrets
    kind: ClusterSecretStore
  target:
    name: mongodb-secret
  dataFrom:
    - extract:
        key: fiware/mongodb-secret
