apiVersion: v2
name: timescaledb-single
description: Chart holder for Timescale DB Single. Based on https://github.com/timescale/timescaledb-kubernetes and adapted for OpenShift.

type: application
version: 0.1

keywords:
  - timescale
  - helm
  - chart
sources:
  - https://github.com/FIWARE-Ops/marinera/tree/main/applications/timescaledb-single

dependencies:
#home: copy of https://github.com/timescale/timescaledb-kubernetes
- name: timescaledb-single
  version: 0.11.0
  repository: file://./timescaledb-single