apiVersion: v2
name: timescaledb-single
description: Chart holder for Timescale DB Single. Based on https://github.com/timescale/timescaledb-kubernetes and adapted for OpenShift.

type: application
version: 1.0.0
appVersion: "pg14.2-ts2.6.1-p2" # PostgreSQL v14.2 TimescaleDB v2.6.1-p2

keywords:
  - timescale
  - helm
  - chart
sources:
  - https://github.com/FIWARE-Ops/marinera/tree/main/applications/timescaledb-single/chart

dependencies:
#home: copy of https://github.com/timescale/timescaledb-kubernetes
- name: timescaledb-single
  version: 0.11.0
  repository: file://./timescaledb-single
maintainers:
  - name: Felipe Roca
    email: felipe@hopu.org
  - name: Alvaro Lopez
    email: alopezme@redhat.com
  - name: Stefan Wiedemann 
    email: stefan.wiedemann@fiware.org
