timescaledb-single:
  secrets:
    credentials:
      PATRONI_SUPERUSER_PASSWORD: "test"
      PATRONI_REPLICATION_PASSWORD: "test"
      PATRONI_admin_PASSWORD: "test"

  persistentVolumes:
    data:
      size: 5Gi
    wal:
      size: 1Gi

#  resources:
#    limits:
#      cpu: 2000m
#      memory: 2Gi
#    requests:
#      cpu: 500m
#      memory: 500Mi

  rbac:
    create: true
    # Specific of this chart. Creates anyuid Role and RoleBinding for the timescaledb SA to run.
    openshift: true
