apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fiware-orion-ld
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/FIWARE-Ops/fiware-gitops
    targetRevision: HEAD
    path: aws/fiware/orion-ld
  destination:
    name: in-cluster
    namespace: fiware
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
