apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: timescaledb-single
  namespace: labs-ci-cd
spec:
  destination:
    namespace: demo
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
      releaseName: timescaledb-single
    path: applications/timescaledb-single/chart
    repoURL: https://github.com/FIWARE-Ops/marinera
    targetRevision: main
  syncPolicy:
    automated: {}
