apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: {{ include "keycloak.name" . }}-fiware
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    # argocd.argoproj.io/hook: PostSync
  #   # helm.sh/hook: post-install
  #   argocd.argoproj.io/sync-wave: "0"
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
    realm: {{ include "keycloak.name" . }}-fiware
spec:
  realm:
    id: "fiware-realm"
    realm: "FIWARE Realm"
    enabled: True
    displayName: "FIWARE Realm"
    users:
      - username: "realm_user"
        firstName: "John"
        lastName: "Doe"
        email: "user@example.com"
        enabled: True
        emailVerified: False
        credentials:
          - type: "password"
            value: "12345"
        realmRoles:
          - "offline_access"
        clientRoles:
          account:
            - "manage-account"
          realm-management:
            - "manage-users"
  instanceSelector:
    matchLabels:
      app: {{ include "keycloak.name" . }}