apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: {{ include "keycloak.name" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.keycloak.instances }}
  externalAccess:
    enabled: True 
