apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: {{ include "keycloak.name" . }}-fiware
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    # argocd.argoproj.io/hook: PostSync
  #   # helm.sh/hook: post-install
  #   argocd.argoproj.io/sync-wave: "0"
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
    realm: {{ include "keycloak.name" . }}-fiware
spec:
  realm:
    id: "fiware-realm"
    realm: "FIWARE Realm"
    enabled: True
    displayName: "FIWARE Realm"
    roles:
      client:
        "orion-pep":
          - name: admin
            composite: false
            clientRole: true
          - name: producer
            composite: false
            clientRole: true
          - name: subscriber
            composite: false
            clientRole: true
            attributes: {}
          - name: consumer
            composite: false
            clientRole: true
    clients:
      - clientId: fiware-login
        enabled: true
        baseUrl: http://localhost:8080
        adminUrl: http://localhost:8080
        redirectUris:
          - http://localhost:8080/*
        defaultClientScopes:

        
          - roles
        publicClient: true
        directAccessGrantsEnabled: true
      - clientId: orion-pep
        enabled: true
        baseUrl: http://localhost:8080
        adminUrl: http://localhost:8080
        redirectUris:
          - http://localhost:8080/*
        defaultClientScopes:
          - roles
        secret: secret
        directAccessGrantsEnabled: true
        authorizationServicesEnabled: false
    users:
      - username: "admin-user"
        firstName: "Admin"
        lastName: "User"
        email: "admin-user@example.com"
        enabled: True
        emailVerified: False
        credentials:
          - type: "password"
            value: "admin-user"
        clientRoles:
          account:
            - "view-profile"
            - "manage-account"
      - username: "consumer-user"
        firstName: "Consumer"
        lastName: "User"
        email: "consumer-user@example.com"
        enabled: True
        emailVerified: False
        credentials:
          - type: "password"
            value: "consumer-user"
        clientRoles:
          account:
            - "view-profile"
            - "manage-account"
      - username: "subscriber-user"
        firstName: "Subscriber"
        lastName: "User"
        email: "subscriber-user@example.com"
        enabled: True
        emailVerified: False
        credentials:
          - type: "password"
            value: "subscriber-user"
        clientRoles:
          account:
            - "view-profile"
            - "manage-account"
    
  instanceSelector:
    matchLabels:
      app: {{ include "keycloak.name" . }}