apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: {{ include "keycloak.name" . }}-fiware
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    # argocd.argoproj.io/hook: PostSync
  #   # helm.sh/hook: post-install
  #   argocd.argoproj.io/sync-wave: "0"
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
    realm: {{ include "keycloak.name" . }}-fiware
spec:
  realm:
    id: "fiware-realm"
    realm: "fiware-realm"
    enabled: True
    displayName: "FIWARE Realm"
    roles:
      realm:
        - name: user
          description: User privileges
          composite: false
          clientRole: false
      client:
        "orion-pep":
          - name: admin
            composite: false
            clientRole: true
          - name: producer
            composite: false
            clientRole: true
          - name: subscriber
            composite: false
            clientRole: true
            attributes: {}
          - name: consumer
            composite: false
            clientRole: true
    clients:
      - clientId: fiware-login
        enabled: true
        baseUrl: http://localhost:8080
        adminUrl: http://localhost:8080
        redirectUris:
          - http://localhost:8080/*
        defaultClientScopes:
          - roles
        publicClient: true
        directAccessGrantsEnabled: true
      - clientId: orion-pep
        enabled: true
        baseUrl: http://localhost:8080
        adminUrl: http://localhost:8080
        redirectUris:
          - http://localhost:8080/*
        defaultClientScopes:
          - roles
        secret: secret
        directAccessGrantsEnabled: true
        authorizationServicesEnabled: true
        authorizationSettings:
          allowRemoteResourceManagement: true
          policyEnforcementMode: ENFORCING
          resources:
            - name: Default Resource
              type: urn:orion-pep:resources:default
              ownerManagedAccess: false
              attributes: {}
              uris:
                - "/*"
          policies:
            - name: Admin policy
              description: Only admin users
              type: role
              logic: POSITIVE
              decisionStrategy: UNANIMOUS
              config:
                roles: '[{"id":"orion-pep/admin","required":false}]'
            - name: Admin users
              type: resource
              logic: POSITIVE
              decisionStrategy: UNANIMOUS
              config:
                resources: '["Default Resource"]'
                applyPolicies: '["Admin policy"]'
          decisionStrategy: UNANIMOUS     
    users:
      - username: "admin-user"
        firstName: "Admin"
        lastName: "User"
        email: "admin-user@example.com"
        enabled: True
        emailVerified: False
        credentials:
          - type: "password"
            value: "admin-user"
        realmRoles:
          - user
        clientRoles:
          account:
            - "view-profile"
            - "manage-account"
          orion-pep:
            - admin
      - username: "consumer-user"
        firstName: "Consumer"
        lastName: "User"
        email: "consumer-user@example.com"
        enabled: True
        emailVerified: False
        credentials:
          - type: "password"
            value: "consumer-user"
        realmRoles:
          - user
        clientRoles:
          account:
            - "view-profile"
            - "manage-account"
          orion-pep:
            - consumer
      - username: "producer-user"
        firstName: "producer"
        lastName: "User"
        email: "producer-user@example.com"
        enabled: True
        emailVerified: False
        credentials:
          - type: "password"
            value: "producer-user"
        realmRoles:
          - user
        clientRoles:
          account:
            - "view-profile"
            - "manage-account"
          orion-pep:
            - producer
      - username: "subscriber-user"
        firstName: "Subscriber"
        lastName: "User"
        email: "subscriber-user@example.com"
        enabled: True
        emailVerified: False
        credentials:
          - type: "password"
            value: "subscriber-user"
        realmRoles:
          - user
        clientRoles:
          account:
            - "view-profile"
            - "manage-account"
          orion-pep:
            - subscriber
    
  instanceSelector:
    matchLabels:
      app: {{ include "keycloak.name" . }}