apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: {{ include "keycloak.name" . }}-admin
  annotations:
    argocd.argoproj.io/hook: PostSync
  #   # helm.sh/hook: post-install
  #   argocd.argoproj.io/sync-wave: "0"
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
    realm: {{ include "keycloak.name" . }}-fiware
spec:
  user:
    username: "realm_user"
    firstName: "John"
    lastName: "Doe"
    email: "user@example.com"
    enabled: True
    emailVerified: False
    credentials:
      - type: "password"
        value: "12345"
    realmRoles:
      - "offline_access"
    clientRoles:
      account:
        - "manage-account"
      realm-management:
        - "manage-users"
  realmSelector:
    matchLabels:
      app: {{ include "keycloak.name" . }}
      realm: {{ include "keycloak.name" . }}-fiware
