name: Create namespace on new branch

on:
  create:
    branches:
      - 'feature-**'

jobs:

  create:
  
    runs-on: ubuntu-latest
    steps:

      - name: Git checkout
        uses: actions/checkout@v1

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1

        with:
          # URL to your OpenShift cluster.
          # Refer to Step 2.
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}

          # Authentication Token. Can use username and password instead.
          # Refer to Step 3.
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}

          # Disables SSL cert checking. Use this if you don't have the certificate authority data.
          insecure_skip_tls_verify: true

      - name: Create namespace
        run: |
          oc new-project ${GITHUB_REF##*/}
          oc adm policy add-role-to-group admin lodestar-developers -n ${GITHUB_REF##*/}

      - name: Rename target branch
        run: |
          find . -type f -name "app.yaml" -exec sed -i'' -e 's/namespace: demo/namespace: ${GITHUB_REFF##*/}/g' {} +
          find . -type f -name "app.yaml" -exec sed -i'' -e 's/name: /name: ${GITHUB_REFF##*/}-/g' {} +
          find . -type f -name "app.yaml" -exec sed -i'' -e 's/targetRevision: main/targetRevision: ${GITHUB_REFF##*/}/g' {} +

      - name: Deploy applications
        run: |
          # apply argo apps
          find . -name 'app.yaml' -exec oc apply -f {} \;
          # label them with their destination-namespace for better selection
          find . -name 'app.yaml' -exec oc label destination-namespace=${GITHUB_REFF##*/} -f {} \;