apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fiware-cluster-secrets
spec:
  provider:
    vault:
      server: "http://cluster-vault.vault.svc:8200"
      path: "fiware"
      version: "v2"
      auth:
        kubernetes:
          mountPath: kubernetes/
          role: secret-reader
          serviceAccountRef:
            name: vault-secret-reader
            namespace: external-secrets-operator
